[tools]
node = '24'
# The Nix package version is too old
claude-code = 'latest'

[settings]
env_file = '.env'

[settings.node]
# Seems not to be working...
# Though it's natural for NixOS to build a binary from source code
compile = false

[tasks.add-serena-claude]
description = "Add Serena MCP server to Claude Code"
run = "claude mcp add serena -s project -- uvx --from git+https://github.com/oraios/serena serena start-mcp-server --context ide-assistant --project $(pwd)"
